language: ruby
bundler_args: --without development
cache: 
  bundler: true
  directories:
    - node_modules
rvm:
  - "1.9.2"
  - "1.9.3"
  - jruby-19mode # JRuby in 1.9 mode - getsource uses C extension.
matrix:
  allow_failures:
    - rvm: jruby-19mode
before_script:
  - mongo harp_test --eval 'db.addUser("harp", "harp");'
  - gem install source2swagger
  - npm install -g jamjs
  - jam install
  - npm install -g bower
  - npm install http-browserify
  - bower install
  - ./script/document
services: mongodb
